### ISSUE TITLE
pin entry is too limited

### ISSUE THREAD

**Issue by rwky** [cotechde/termbot#1]
## Bug description

I'm not sure which repo is looking after termbot this one or 
https://github.com/open-keychain/termbot/issues/28
So I'll copy this here. The pin entry in the latest version on Google play only accepts up to 10 numeric digits, it should allow more and alphanumeric characters.

## Steps to reproduce

1. Use any key with a pin that doesn't match above

## Expected behavior

It should allow any pin

## Android device

 - Device: Samsung galaxy s10
 - OS: android 9
 -TermBot Version: 1.9.5 from play store

**Comment by dschuermann** [comment]
I released a new version that allows a fallback to keyboard input.

However, we recommend a numeric PIN as there is no need to choose a difficult and long PIN with other characters.

Security Keys and Smartcards have a vastly different threat model than password-encrypted files or Internet accounts. While the latter can be brute-forced by trying all possible combinations of different password-lengths, security keys and smartcards get locked after 3 failed PIN attempts. Then, the card needs to be unlocked again using the PUK (also called Admin-PIN). After 3 failed attempts using the PUK, the card is finally blocked and can only be resetted completely.

Thus, even when choosing a short numeric PIN (the standard recommends 6 digits), the probability that an attacker can guess the correct PIN is negligible low.

(parts of this have been added to the FAQ at https://hwsecurity.dev/termbot/#faq)

**Comment by demure** [comment]
Thanks for working on this.
My main usecase for an alphanumeric pin isn't to try to make a 'complicated' pin, but rather one that I will remember. (a few rounds of diceware)

**Comment by dschuermann** [comment]
@demure To understand this more: You are using $n words instead of $n digits? And this is easier for you to remember?

**Comment by demure** [comment]
> @demure To understand this more: You are using $n words instead of $n digits? And this is easier for you to remember?

Yep, for me the "meaningful nonsense" style, such as the one described by this xkcd https://xkcd.com/936/, sticks in my head better. Just a personal preference, since numbers don't stick in my head as well.

**Comment by dschuermann** [comment]
> > @demure To understand this more: You are using $n words instead of $n digits? And this is easier for you to remember?
> 
> Yep, for me the "meaningful nonsense" style, such as the one described by this xkcd https://xkcd.com/936/, sticks in my head better. Just a personal preference, since numbers don't stick in my head as well.

Okay, I see, thanks for the insights.
