### ISSUE TITLE
Can't enter pincode

### ISSUE THREAD

**Issue by Vashiru** [cotechde/termbot#10]
Description of the problem:
I have a Yubikey NEO (4th gen). I've added this to Termbot via NFC and want to use this to set up an SSH connection. When I connect to the server it will prompt me for my pincode but the screen won't respond to any input.

Scenario:
1. Add the yubikey ssh key to termbot
2. Configure a server to use this ssh key to connext
3. You'll be prompted for a pincode
4. None of the buttons on this panel respond to any input. 

I've tried holding my yubikey against it to see if it was a matter of it being present but it wasn't.

I've also tested the screen where you add the key, where it says "just do it or click for help", clicking isn't actually responding for me there either. 

Device: OnePlus 5T

**Comment by dschuermann** [comment]
Are you using an app that does a full Android overlay? Such as color filter apps, e.g. Twilight?

Try disabling it.

**Comment by dschuermann** [comment]
Fixed in the newest version on Google Play.

**Comment by Vashiru** [comment]
Can confirm this fixes the issue. Thanks @dschuermann!
