### ISSUE TITLE
Support for Ed25519 on OpenPGP Cards

### ISSUE THREAD

**Issue by tkren** [cotechde/termbot#11]
## Bug description
TermBot crashes when adding an ed25519 auth key stored on Nitrokey Start.

The Crash log shows that exception `java.lang.UnsupportedOperationException` is thrown in method `getKeyFormatParser` in `de.cotech.hw.openpgp.internal.openpgp.EdDSAKeyFormat` at line 47 of `EdDSAKeyFormat.java`.

## Steps to reproduce

1. Go to 'Manage Pubkeys'
2. Click on 'Add hardware security key' icon
3. Insert OTG adapter and Nitrokey Start
4. Allow TermBot to access Nitrokey Start
5. Suddenly, we are in the Hosts lists again
6. Do step 1 to 4 again
7. TermBot crashes

## Android device

 - OS: Android 9 00EEA_1_39D
 - ConnectBot Version: 1.9.5-75-c1a3b88-termbot

**Comment by dschuermann** [comment]
Confirmed. We haven't gotten around to implement the Ed25519 parser.

**Comment by Raybuntu** [comment]
I'm having the same issue with my Yubikey 5 NFC both with USB and NFC. Any update on this one?

**Comment by Django-BOfH** [comment]
HI Dominik,

as you wrote me on 22nd of November:

> Ed25519 is unfortunately not yet supported

Are there already plans when termbot ed25519 will support keys?

**Comment by disassembler** [comment]
Having this issue as well. Would be great if support could be added.

**Comment by Django-BOfH** [comment]
Can you already make a statement if and when the ED25519 support will be implemented?

**Comment by elijahmathews** [comment]
Same issue here with a Yubikey 5 NFC. Would love `ed25519` support for SSH authentication.

**Comment by doitian** [comment]
OpenKeychain 5.7 has fixed a ed25519 issue and I can use the key to pull in the app AndroidPasswordStore. Not sure whether it can help in termbot:

* https://github.com/open-keychain/open-keychain/commit/64f4d7aaa494e9121a6ca7da484402a4553b7838
* https://github.com/open-keychain/open-keychain/commit/3fb47716024700ccb29888ca2d1ea9d4f2d1cc9b

**Comment by dschuermann** [comment]
Yup, I am working on it.

**Comment by dschuermann** [comment]
I just released a new version, which should be available soon on Google Play. It should support Ed25519.
