### ISSUE TITLE
Accept entered pin once token is near

### ISSUE THREAD

**Issue by klaernie** [cotechde/termbot#14]
After entering my PIN for my NFC token I often miss to confirm this, and touch my token immediately. This of cause doesn't work, triggers me to touch the OK button and then I need to touch my token again.

I understand that this is a required feature for USB based tokens, as they don't have a separate trigger possibly like NFC tokens.

My ideal solution would be that if during PIN entry a NFC token is touched the PIN entered so far would be used without requiring the user to manually confirm.

**Comment by dschuermann** [comment]
Hmh, interesting idea to require one click less. I will evaluate this.

**Comment by dschuermann** [comment]
I implemented this internally, will be available in the next Termbot release.

**Comment by dschuermann** [comment]
This has been released.

**Comment by klaernie** [comment]
Awesome, that's really cool. Thanks a lot!
