### ISSUE TITLE
PIN length for the internal pinpad

### ISSUE THREAD

**Issue by ei-ke** [cotechde/termbot#18]
## Is your feature request related to a problem? Please describe.

The internal pinpad only accepts up to 10 digits.

## Describe the solution you'd like

Increase the accepted PIN length you can enter with the internal pinpad to a reasonable length.

## Describe alternatives you've considered

Switching to "abc" and using the "normal" keyboard is a feasible workaround.

**Comment by dschuermann** [comment]
Security Keys and Smartcards have a vastly different threat model than password-encrypted files or Internet accounts. While the latter can be brute-forced by trying all possible combinations of different password-lengths, security keys and smartcards get locked after 3 failed PIN attempts. Then, the card needs to be unlocked again using the PUK (also called Admin-PIN). After 3 failed attempts using the PUK, the card is finally blocked and can only be resetted completely.

Thus, even when choosing a short numeric PIN (the standard recommends 6 digits), the probability that an attacker can guess the correct PIN is negligible low.

Conclusively, a "reasonable lengthed" PIN is below 10 digits.

**Comment by erayd** [comment]
@dschuermann Why is this a valid reason to *restrict* the length though? It's certainly a good argument, but if a user wishes to use something longer, why not simply let them?

**Comment by ei-ke** [comment]
@dschuermann thank you for the explanation. I already knew this. It shouldn't mean 10 digits is insecure or similar. I just thought it's a simple change to the source code.

**Comment by dschuermann** [comment]
Hmm, what are your chosen PIN length and why did you choose them this long?

**Comment by ei-ke** [comment]
Let's say 16 digits would be my wish. I'll send you an email later.

**Comment by dschuermann** [comment]
Thanks for your feedback. The next version will allow up to 16 digits. With this decision we are following the design of the Android OS that also allows up to 16 digits for the lockscreen.

Also, I implemented a long-click for the delete button to clear the full input.

**Comment by dschuermann** [comment]
This has been released.
