### ISSUE TITLE
Renaming Smart Cards

### ISSUE THREAD

**Issue by TychoSchenkeveld** [cotechde/termbot#2]
## Describe the solution you'd like
Adding a facility to rename each card from the default (e.g. "Yubikey (xxxxxx)"). To something like "Customer X" or "Home"

## Describe alternatives you've considered
The current setup is enough to discern between them but the serial numbers don't mean anything to me. I've got several of them and I gave them all names. I'd like to use the same names I use in other apps. Just allowing us to rename them should do this.

Also, some cards (Fidesmo in particular) are all reporting themselves with the same number.

**Comment by dschuermann** [comment]
will be in the next update: https://github.com/cotechde/termbot/commit/8b9c46d17cc8541d8c1f0fdfaad9dd01d8884ec6

**Comment by TychoSchenkeveld** [comment]
Wow that's quick, thanks!!
