### ISSUE TITLE
Hardware keyboard input when entering PIN (no feedback)

### ISSUE THREAD

**Issue by TychoSchenkeveld** [cotechde/termbot#20]
## Is your feature request related to a problem? Please describe.
With OpenKeyChain it was possible to use a hardware keyboard when entering the PIN.This is no longer possible with Termbot, I must use the touchscreen.

This is an issue with DeX because I have to use the mouse to click on the pin keypad, which means everyone around me can see me inputting the PIN.

## Describe the solution you'd like
The hardware keyboard to simply work on the PIN input screen (without lighting up the keys on the keypad when pressed!)

## Describe alternatives you've considered
None

**Comment by dschuermann** [comment]
Thanks for the feedback. We implemented this internally. Will be part of the next Termbot release.

**Comment by TychoSchenkeveld** [comment]
Thanks!!

**Comment by dschuermann** [comment]
This has been released.
