### ISSUE TITLE
Yubikey: No Cryptographic Key found in this Security Key

### ISSUE THREAD

**Issue by mars-online** [cotechde/termbot#22]
I use a Yubikey 5 NFC and OpenPGP already works since I can use it to encrypt/decrypt/sign with Open KeyChain.

Trying to use it to add the key in the Pukey Menu of TermBot I only get the message "No Cryptographic Key found on the Security Key".

Might this be a bug or is there an extra step I need to follow before adding the key?

What can I provide to make the diagnosis easier?

**Comment by dschuermann** [comment]
Does it work for you on your desktop computer with gpg and OpenSSH?

There are always 3 PGP subkeys on a Yubikey:
- signing
- encryption
- authentication

Termbot uses the authentication subkey. Thus, even when OpenKeychain works with signing and encrypting emails, it does not automatically mean authentication works.

**Comment by erayd** [comment]
It's also possible to set only some of those slots. What does `gpg --card-status` say?

**Comment by mars-online** [comment]
Sorry for the fuzz - it was indeed something wrong with the auth key. I guess it had a defect or the Yubikey malfunctioned. I generated and keytocarded a new auth key and it works now.
