### ISSUE TITLE
"Use external provider" option missing 

### ISSUE THREAD

**Issue by sentriz** [cotechde/termbot#28]
Hi

I have some SSH subkeys in my gpg key, provided by OpenKeychain

I just upgraded from 1.9.3 to 1.9.5. On the old version when I added a new host under "Use pubkey authentication" there was a "Use external agent" or similar option.
But now after upgrading I don't see the option

Also under "manage pubkeys" I see some hardware options but nothing about using OpenKeychain to access my SSH subkeys

Thank you :)

**Comment by dschuermann** [comment]
Yup, OpenKeychain support has been removed: https://hwsecurity.dev/termbot/#faq

**Comment by sentriz** [comment]
if I'm reading the FAQ right, the only way to use authentication subkeys now is to export them to a file for termbot?

I think it's a shame because I recently merged my ssh keys to my gpg key, hoping I could forget about my ssh key files. 

are there any alternative routes I could go?

thank you :+1:

**Comment by dschuermann** [comment]
I don't know of alternative ways, sry.
I would advise against using the same OpenPGP key for email encryption and SSH, but that's my personal opinion.

What I can recommend is using a Yubikey 5 NFC for SSH authentication.

**Comment by erayd** [comment]
@dschuermann Why did you remove OpenKeychain support anyway? It just feels like a shitty marketing tactic for the new SDK you are also selling. Nothing wrong with making money from software, but this was IMO the wrong way to go about it.

Support via OpenKeychain was notably superior to the built-in implementation in a number of respects, and I can't think of any valid technical reason for its removal. I would happily pay something to get OpenKeychain support back. Perhaps it could become an optional paid feature?

**Comment by dschuermann** [comment]
Small reasons are code complexity (IPC calls between Android apps) and bad UX. And the main reason: I myself no longer stand behind the idea of using the same OpenPGP key for different network protocols.

You can fork the last version with OpenKeychain support here: https://github.com/open-keychain/termbot

**Comment by michalzxc** [comment]
That is disappointing, I was using Termbot mainly because of GPG key support

**Comment by luke-clifton** [comment]
You can still install an old version from fdroid that works.
