### ISSUE TITLE
4096-bit RSA key on yubikey 5c hangs while attempting to authenticate.

### ISSUE THREAD

**Issue by JLSchuler99** [cotechde/termbot#38]
I have a 4096bit RSA key stored on a yubikey 5c and it works perfectly for ssh authentication on my pc, but not in termbot on my android. I am able to add the key in termbot, and  even confirm the pubkey it import is correct, but when it attempts to authenticate, it simply hangs.
I noticed RSA 2048 is the only option for generating keys in this app, are other RSA key sizes supported?

Thanks in advance.

**Comment by dschuermann** [comment]
>  I noticed RSA 2048 is the only option for generating keys in this app, are other RSA key sizes supported?

Where do you see this?

How did you install the app? On Google Play or F-Droid?

**Comment by JLSchuler99** [comment]
I installed the app from F-Droid and under "Setup Key with: " the only RSA option is 2048. To be clear, I've set up 4096bit keys on a different machine, and they work great for everything except termbot.

**Comment by dschuermann** [comment]
The F-Droid version is very old, hasn't been updated in a long time.

**Comment by dschuermann** [comment]
Hm, okay looks like it has been updated on 2021-04-14.

Can you please provide a screenshot where it only says RSA 2048?
