### ISSUE TITLE
No "Use external agent"

### ISSUE THREAD

**Issue by biegacz1** [cotechde/termbot#39]
There used to be option "use external agent" but since update it's no longer present. I can't use OpenKeychain to authenticate to server with my gpg key.
Was this option removed?

**Comment by erayd** [comment]
Yup. The project maintainer decided to remove OpenKeychain support in favour of his own commercial API.

This is really annoying for my workflow; especially #7, which is still open two years later.

**Comment by dschuermann** [comment]
To clarify: I am maintaining Termbot, OpenKeychain and the Hardware Security SDK.
Reasons why I moved to the SDK are here: https://github.com/cotechde/termbot/issues/28
