### ISSUE TITLE
Not working with Yubikey 4 Nano (USB-C) through USB-OTG

### ISSUE THREAD

**Issue by TychoSchenkeveld** [cotechde/termbot#6]
## Bug description
On my Samsung Galaxy Tab S (without NFC) I often use a Yubikey 4 Nano with an OTG adapter to Micro-USB (as the Tab S doesn't have USB-C either :) ). With the new Termbot this no longer works, I can add it under pubkeys just fine, but when I try to authenticate it doesn't light up after entering the PIN.

## Steps to reproduce

1. Go to a Server
2. Click on Connect
3. Enter PIN
4. Wait for device to flash (I have touch to sign enabled)

## Expected behavior
Device should flash, I would tap it and it signs in.

**Please note this does work fine with the old version (with OpenKeyChain)**. So I think it's a bug in the new library.

I already tried disconnecting/connecting the device, and tapping it of course.

## Screenshots
I don't really have any as there is no error message, it just waits on the prompt to connect the smart card. But I can make some if you like.

## Android device

 - Device: Samsung Galaxy Tab S
 - OS: Android 6
 - TermBox the latest in the app store :)

Let me know if you need any logs or anything!

**Comment by dschuermann** [comment]
I just released a new version on Google Play (Version 1.9.5-termbot3). Can you please try this one and report if this fixes your issue?

**Comment by TychoSchenkeveld** [comment]
I tested this weekend and it works indeed! Thanks very much for the quick fix!
