### ISSUE TITLE
Remember PIN input type

### ISSUE THREAD

**Issue by erayd** [cotechde/termbot#8]
## Is your feature request related to a problem? 
If OpenKeychain is used with an alphanumeric PIN, then the next time the PIN entry screen is displayed, it defaults to alphanumeric entry. TermBot doesn't do this, and simply defaults to digit-only entry every time.

## Describe the solution you'd like
Have TermBot default to the last-used entry mode when prompting for a PIN.

## Describe alternatives you've considered
There are no available workarounds in I'm aware of - currently I need to press the 'abc' button every time.

**Comment by dschuermann** [comment]
I'll put it on our roadmap. But I cannot give an ETA.

**Comment by dschuermann** [comment]
I just released a new version on Google Play. This is now implemented.

Please report back. If the issue still exist, we can re-open the bug report.

**Comment by erayd** [comment]
Thank you :-). I can confirm that this is working correctly.
